---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: user-group-operator deploy
  name: user-group-operator-build

parameters:
- name: KOPF_S2I_IMAGE
  value: quay.io/redhat-cop/python-kopf-s2i:v1.36
- name: GIT_REPO
  value: https://github.com/rhpds/openshift-user-auth-tracker.git
- name: NAME
  value: openshift-user-auth-tracker

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${KOPF_S2I_IMAGE}
    triggers: []
