# Development

Development on this operator can be performed in the `odo` OpenShift developer CLI or building with OpenShift build configs.
An OpenShift cluster with cluster-admin is required for `odo` development.
https://developers.redhat.com/products/codeready-containers/overview[CodeReady Containers] is recommended for local development.

## Development with `odo`

Use of `odo` is recommended for fast iterative development.
`odo` simplifies the build/deploy process and avoids creating unnecessary build artifacts during the development process.

. Install the `odo` developer CLI as described in the OpenShift documentation:
https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html[Installing odo]

. Create resources required for development from helm chart:
+
--------------------------------------------
helm template helm/ \
--include-crds \
--set deploy=false \
--set namespace.name=openshift-user-reaper \
| oc apply -f -
--------------------------------------------

. Change project namespace to `openshift-user-reaper`:
+
--------------------------------
oc project openshift-user-reaper
--------------------------------

. Grant privileges for cluster role `openshift-user-reaper` to default service account:
+
-----------------------------------------------------------------------
oc adm policy add-cluster-role-to-user openshift-user-reaper -z default
-----------------------------------------------------------------------

. Setup `odo` from the provided `devfile.yaml`:
+
---------------------------------
odo create --devfile devfile.yaml
---------------------------------
+
NOTE: The poolboy operator domain is specified in the devfile.
If you are developing with a different operator domain then you will need to update the `devfile.yaml`.

. Use `odo push` to push code into the odo container:
+
--------
odo push
--------
