---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openshiftUserReaper.name" . }}
  labels:
    {{- include "openshiftUserReaper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - user.openshift.io
  resources:
  - identities
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
{{- range .Values.namespaceCheckResources }}
- apiGroups:
  - {{ .group | default "" | quote }}
  resources:
  - {{ .plural | quote }}
  verbs:
  - get
  - list
{{- end }}
