{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openshiftUserReaper.namespaceName" . }}
  labels:
    {{- include "openshiftUserReaper.labels" . | nindent 4 }}
{{- end -}}
